#!/bin/bash

# pasali / 12.10.2012


case "$1" in
   "-s") 
    
        echo "Downloads dizinindeki 'srt' ve 'sub' uzantılı dosyalar silenecek?(e/h)"
        read secim
        if [ "$secim"==[eE] ]
        then
            rm -rf $HOME/Downloads/*.srt && rm -rf $HOME/Downloads/*.sub
        fi
    exit 1
    ;;
    "-t")
     
        echo "Downloads dizinindeki 'torrent' uzantılı dosyalar silenecek?(e/h)"
        read secim
        if [ "$secim"==[eE] ]
        then
            rm -rf $HOME/Downloads/*.torrent
        fi
    exit 1
    ;;
    "-a")
         
        echo "Downloads dizinindeki tüm  dosyalar silenecek?(e/h)"
        read secim
        if [ "$secim"==[eE] ]
        then
            rm -rf $HOME/Downloads/*
        fi
        ;;
    "-n")
        
        path=$(find Downloads/ -type f -name $2)
        echo $path
        echo "Silinsin mi?(e/h)"
        read secim
        if [ "$secim"==[eE] ]
        then
            rm -rf "$path"
        fi
        ;;
     "-e")
        
        echo "$2 uzantılı dosyalar silinecek?(e/h)"
        read secim
        if [ "$secim"==[eE] ]
        then
            rm -rf Downloads/*."$2"
        fi
        ;;

esac
